version: '3.3'
services:
  jupyter-lab:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./tf-deep-learning:/tf-deep-learning
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
              count: 1
          

